### Pre-procesamiento de datos (Pre-processing data)
Tambien conocido como  Data Cleaning o Data Cleansing.

Este proceso involucra detectar, eliminar, corregir o transformar cualquier anomalia, perturbacion o irrelevancia en los datos.


## Arreglos
Para el manejo de datos cuantitativos Python cuenta con una estructura llamada `array` que está disponible en el paquete `NumPy`.  

Un array o arreglo se entiende como una matriz de elementos organizados en filas y columnas. 

### Crear una matriz NumPy

La forma más sencilla de crear un arreglo en Numpy es usar listas. Puedes convertir una lista de Python en un arreglo de numpy utilizando el objeto `np.array`.

Antes de hacerlo, debes importar el paquete usando la expresión `import`:

>import numpy as np

In [1]:
import numpy as np
myList = [1,5,3,2]
numpy_array_from_list = np.array(myList)
print(numpy_array_from_list)
print(type(myList))
print(type(numpy_array_from_list))

[1 5 3 2]
<class 'list'>
<class 'numpy.ndarray'>


## 

### operaciones matematicas en un arreglo

Se puede realizar operaciones matematicas como sumas, restas, divisiones y multiplicaciones en un arreglo. La sintaxis es el nombre de la matriz seguido de la operacion (+, -, *, /) seguidas del operado

In [2]:
numpy_array_from_list + 100

array([101, 105, 103, 102])

### Forma del arraglo
Puedes comprobar la forma del arreglo llamado al objeto `shape` precedido por el nombre del arreglo. De la misma mnera, puedes verificar su tipo con dtypes.

El tipo indicado al usar el metodo `dtype` esta dado por los datos dentro de la matriz, si todos son enteros la repuesta sera int64 pero con solo uno que sea float por ejemplo el tipo de dato de la matriz sera float64, el codigo del tipo cambia tomando en cuenta todos los tipos.

In [7]:
a = np.array([1,2,3,1.33,"?"])
print(a)
print(a.shape)
print(a.dtype)

['1' '2' '3' '1.33' '?']
(5,)
<U32


In [8]:
d = np.array([[1,2,3],[10,11,12]])
print(d)
print(d.shape)

[[ 1  2  3]
 [10 11 12]]
(2, 3)


### np.zeros y np.ones
Puedes crear un arreglo lleno de ceros o unos usando los comandos np.zeros y np.ones respectivamente.

In [10]:
# unos
A = np.ones((2,3))
print(A)
# ceros
B = np.zeros((3,4))
print(B)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Cambiar la forma de los datos
El algunos ocasiones, es necesario cambiar la forma de los datos de ancho a largo. Puedes utilizar la funcion `reshape` para esto:

In [11]:
e = np.array([(1,2,3),(4,5,6)])
print(e)
e.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

### Extraer informacion de arreglos es basicamente igual que en las listas
Al tratar con mas de una dimension, se debe considerar un indice para cada dimension


In [15]:
print("matris completa ")
print(e)
print("elementos")
print(e[0])
print(e[1])

matris completa 
[[1 2 3]
 [4 5 6]]
elementos
[1 2 3]
[4 5 6]


In [16]:
print("matris completa ")
print(e)
print("elementos")
print(e[:, 0])
print(e[:, 1])
print(e[:, 2])

matris completa 
[[1 2 3]
 [4 5 6]]
elementos
[1 4]
[2 5]
[3 6]


In [17]:
print("matris completa ")
print(e)
print("elementos")
print(e[0,0])
print(e[0,1])
print(e[1,1])

matris completa 
[[1 2 3]
 [4 5 6]]
elementos
1
2
5


La diferencia clave entre un arreglo y una lista es que los arreglos estan diseñados para mejar opearciones vectoriales, mientras que una lista de Python no lo esta.

Esto significa que si aplicas una funcion, se realiza en cada elemento del arreglo, en luga de en todo el objeto de la matriz.


In [18]:
# e es un arreglo definido previamente
D = e + 2
print(D)
  

[[3 4 5]
 [6 7 8]]


In [19]:
# odd es una lista
dd = [1,3,5]
# odd + 2 esta operacion genera un error